baseURL = "https://shiyujin0.github.io/"
title = "Shiyu Jin's Personal Homepage"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = "G-4KBSJL08XE"
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, Shiyu Jin"

# Configuration Features
[params]
  description = "I am a software engineer at Waymo working on multi-modal large language models for Autonomous Driving."      # Your meta description of the site
  header_title = "Shiyu Jin"                 # Your header title
  header_subtitle = "Software Engineer @ Waymo, Ph.D. UC Berkeley" # Your header subtitle
  header_email = "Email: jsy [at] berkeley [dot] edu"
  home_image = "/images/shiyujin.jpg"          # Path to header image starting from the static directory (optional)
  recent_posts = 0                           # Max amount of recent posts to show
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-2x"
    href = "https://www.linkedin.com/in/shiyu-jin-320553124/"
  [[params.social]]
    fa_icon = "ai ai-google-scholar-square ai-2x"
    href = "https://scholar.google.com/citations?user=GdYgso8AAAAJ&hl=en"


