baseURL = "https://shiyujin.github.io/"
title = "Shiyu Jin's Personal Homepage"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = "G-4KBSJL08XE"
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, Changhao Wang"

# Configuration Features
[params]
  description = "I am a researcher at Meta FAIR working on robotics manipulation and embodied AI."      # Your meta description of the site
  header_title = "Changhao Wang"                 # Your header title
  header_subtitle = "Researcher @ Meta FAIR, Ph.D. UC Berkeley" # Your header subtitle
  header_email = "Email: changhaowang [at] meta [dot] com"
  home_image = "/images/changhao.jpg"          # Path to header image starting from the static directory (optional)
  recent_posts = 0                           # Max amount of recent posts to show
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-2x"          # Font Awesome icon class
    href = "https://github.com/ChanghaoWang"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-2x"
    href = "https://www.linkedin.com/in/changhaowang0708/"
  [[params.social]]
    fa_icon = "ai ai-google-scholar-square ai-2x"
    href = "https://scholar.google.com/citations?user=TI15S8IAAAAJ&hl=en&authuser=2"